# Application
spring.application.name=dvelupmint

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JWT Configuration (using email)
jwt.secret=${JWT_SECRET}

# Server
server.port=8080

# Hibernate
spring.jpa.hibernate.ddl-auto=update
